---
title: "Philosophy Journey"
subtitle: 'My personal struggle with philosophical questions and ideas.'
format:
  html:
    grid:
      sidebar-width: 0px
      body-width: 1300px
      margin-width: 200px
      gutter-width: 1.5rem
    include-title: false
    title-block: false
---

# Life Lessons

- Parents: Turns out your parents did their best and also kinda messed you up. But at the end of the day, you’ve got to deal with it.
- No One’s Coming to Save You: No magical mentor, no secret billionaire uncle, not even Batman. It’s just you — and that includes doing basic stuff like folding your laundry before it becomes a roommate.
- Boundaries: That doesn’t just mean blocking someone on Instagram. Say it with me: “No 😊.” See? Revolutionary. You don’t have to be mean or rude.
- Stop Chasing People: Don’t chase people who treat you like an option. You’re not a side quest. If they can’t see that, they can go play somebody else’s game.Real 
- Self-Care: It’s not bath bombs and face masks. It’s getting eight hours of sleep, eating something that grew in the ground, and answering that email before it ruins your week.
- Feelings: Feelings won’t kill you. Crying won’t kill you. Screaming into a pillow won’t kill you. But ignoring your feelings? That’ll destroy you from the inside out.
- Building Yourself: You don’t find yourself — you build yourself. Day by day. Some days you’re leveling up; other days you’re back at square one. Both count.
- It’s Not That Deep: Most of the time, you’re not cursed — you’re just tired, thirsty, and probably overdue for a snack.


# Henry Cavill

- Choose your lifes mate carefully, from this one decision.will come 90% of your happiness or your misery.
- Never deprive someone of Hope, it may be all that they have. 
- Never waste the opportunity to tell someone you love them. 
- Remember that 80% of the sucess on any job is based on your ability to deal with people. 
- Don’t expect life to be fair. 



# Confiance en soi

- "Soyez vous mêmes tous les autres sont déjà pris !" Oscar Wilde

# Bienveillance

- «Chaque personne que tu rencontres mène une bataille dont tu n'as aucune idée. Sois gentil. Toujours.» Robin Williams (1951 – 2014)


# Social

-  "I was ashamed of myself when I realised life was a costume party and I attended with my real face." Franz Kafka (1883 – 1924)


# Self parenting

«What would I do today if I was taking care of my human? That’s your job. The only person that is going to truly take care of <your name> is myself. » Matthew Hussey

# Life meaning

 "Why not? Life is short. Life is dull. Life is full of pain. And this is a chance for something special." Juan Antonio - VICKY CRISTINA BARCELONA(2008)
«The literal meaning of life is whatever you're doing that prevents you from killing yourself. » Albert Camus (1913 – 1960)

CYCLE DE L’ABSURDE
Accepter l’absurde

La condition absurde de Sisyphe
Condamné à pousser une pierre au sommet d'une montagne, qui finit toujours par retomber.  Une tache dénuée de sens mais Sisyphe peut y trouver une forme de liberté. 
Sisyphe incarne l’acceptation lucide et joyeuse de l’absurde.


La condition humaine est absurde
l'homme cherche toujours un sens au monde, un sens à son existence sur terre, un sens à ses actions.  Or le monde dans lequel nous vivons n'a pas de sens. 
Est-ce que la vie vaut la peine d’être vécue ?

- Abandonner la lutte. Se suicider
- Sauter dans la foi. Se réfugier dans la croyance
- Se révolter lucidement. Vivre sans sens mais pleinement
    - CYCLE DE LA RÉVOLTE. Révolter l’absurde. Choisir la vengeance aveugle. Face au vide de sens, choisir de détruire sans bâtir, jusqu’à l’autodestruction (malgré la souffrance).
    La révolte nihiliste et destructrice de Caligula. Après la mort de son amante, Caligula découvre que les hommes meurent et ne sont pas heureux. Ne croyant plus en rien, Il tue, humilie et écrase pour mettre le monde en accord avec l’absurde qu’il a découvert. Caligula incarne la révolte destructrice, l’échec d’une révolte sans mesure.

    - Choisir la création féconde. Face au vide de sens, choisir de construire, de se dépasser, et de donner (malgré la souffrance). La révolte libératrice et créatrice de Prométhée. Condamné à être attaché à un rocher, son foie dévoré par un aigle chaque jour, et repoussant la nuit pour avoir donner le feu aux humains Il s’est révolté pour les autres et a choisi de se sacrifier pour améliorer la condition des hommes. Prométhée incarne la révolte créatrice, le succès d’une révolte mesurée.
        - Toujours avec mesure. Aimer la vie mais sans vouloir la posséder ni lui donner un sens absolu. Se révolter mais sans basculer dans la négation de toute valeur (sinon on tombe dans le nihilisme). Vivre dans la lumière mais en acceptant les limites de notre condition d’êtres mortels et finis.
        CYCLE DE L’AMOUR. Aimer malgré l’absurde. La mesure de Némésis. Némésis est la déesse de la justice et de la mesure, qui punit l’hybris (la démesure des hommes). Elle incarne la limite qu’il faut respecter pour que la révolte reste féconde et ne se transforme pas en tyrannie.

# Vivre sa vie

« Penser sa vie, vivre sa pensée » - André Comte-Sponville
« Apprendre à aimer la vie telle qu’elle est. » - André Comte-Sponville

" Penser sa vie, c'est la penser où elle est : ici et maintenant, certes, mais aussi dans la société, dans l'histoire, dans le monde. Et vivre sa pensée, c'est agir, autant qu'on peut, autant qu'on doit, puisqu'on ne pourrait autrement que subir ou rêver." - André Comte-Sponville


# Amour


D'après Platon (428 - 348 av. J.-C.), il existe trois formes d’amour complémentaires : 

- **Eros (Passion)**: Fondé sur une relation sensuelle, charnelle, sexuelle, éventuellement amoureuse et passionnelle. Ce peut être l’ivresse d’un « coup de foudre » qui induit un fort désir de l’autre. Cela peut être délicieux et… ravageur. Il y a un risque de vivre une illusion, d’aimer l’image de l’autre basée sur des fantasmes et l’imaginaire. Le partenaire peut être vécu comme un objet d’amour conditionnel où l’ego possessif prend toute la place. Si l’attachement à une personne est uniquement conditionné par une passion érotique, le risque de perdition est présent et le Malin peut en faire un terrain de prédilection dévastateur. Cependant l’amour Éros peut initier une relation qui évoluera vers l’amour Philia ou Agapê afin de se vivre harmonieusement au long cours.

-**Philia (Amitié)**: Attachement lié à un sentiment d’amitié, associé à des valeurs, des centres d’intérêts et des objectifs communs. Il prend appui sur des plaisirs partagés, des échanges, du jeu, de la solidarité et de la complicité. La relation est chaleureuse et affective, chacun ayant le souci de l’autre. Cependant, il est conditionnel car fondé sur des activités ou des vécus partagés.

- **Agapê (Charité)**: Amour fraternel, universel, altruiste, spirituel. Il se donne « gratuitement », de manière désintéressée, sans attendre de retour. Il est inconditionnel, accepte l’autre tel qu’il est, avec ses qualités et ses défauts. Il souhaite son bien-être sans profit personnel. Il a de la compassion pour l’autre et l’aime… même s’il n’est pas aimé de lui. C’est un amour affranchi de l’ego qui se situe au-delà de l’émotionnel.

Amour complet : Eros -> Philia + Agapê

« Je rêve d’une personne qui serait ma meilleure amie et ma meilleure amante » (Inconnu)

« Notre plus grande histoire d’amour est derrière nous (amour inconditionel maternel/paternel). Maintenant, il s’agit d’apprendre à aimer autrement et d’accepter d’être aimé autrement. » André Comte-Sponville

# Désir

« Il y a deux tragédies dans la vie. L'une est de ne pas obtenir ce que l'on désire ardemment, et l'autre de l'obtenir »
George Bernard Shaw
Critique musical, dramaturge, essayiste, auteur de pièces de théâtre et scénariste irlandais (1856 - 1950)

- La tragédie du désir insatisfait. Le désir nous pousse à chercher ce qui nous échappe, et cette frustration est inhérente à la condition humaine (e.g., lorsque l’amant n’est pas là, il nous manque).
- La tragédie du désir réalisé. la réalisation du désir ne produit pas le bonheur espéré, mais plutôt de nouvelles souffrances (e.g., lorsque l’amant est là, on commence à s’ennuyer).

# Growing up

« Les enfants commencent par aimer leurs parents ; devenus grands, ils les jugent ; quelquefois, ils leur pardonnent. »
Oscar Wilde (1854-1900)
Écrivain, romancier, dramaturge, et poète irlandais


L’Enfant aime ses parents > L’olescent juge ses parents > Quelquefois, l’adulte pardonne ses parents



# méditation

"Attention totalement pure qui ne demande rien et ne s’addresse à personne.
Il s’agit d’être immobile, attention à tout (bruit, respiration, douleur, démengésons, fantasme, angoisse). Vous observez ce qu’il se passe, le présent qui passe (e.g., respiration). Au moins, ca génère du calme. Au plus, une expérience d’éternité.
Se libérer des angoisses et des désirs pour vivre le présent au présent (autrement dit l’éternité)."
André Comte-Sponville



# Peur

"On est plus souvent effrayé que blessé; et nous souffrons plus dans l'imagination que dans la réalité." - Sénèque (4 av. J.-C. – 65 ap. J.-C.)
"Ce qui trouble les hommes, ce ne sont pas les choses, mais les jugements qu'ils portent sur les choses." - Épictète (50 – 135 ap. J.-C.)
- peur collective: La peur est souvent irrationnelle et amplifiée par les médias et les réseaux sociaux, créant un climat de panique collective.
- peur primordiale (la morte): La peur de la mort est une peur fondamentale qui influence de nombreux aspects de notre comportement et de nos croyances.
- peur de rater sa vie: La peur de ne pas vivre pleinement peut nous pousser à prendre des risques inutiles ou à nous comparer constamment aux autres.

# Mort

« Dire que vous pouvez aimer une personne toute votre vie, c'est comme si vous prétendiez qu'une bougie continuera à brûler aussi longtemps que vous vivrez. »
Léon Tolstoï 

"Memento mori" - "Souviens-toi que tu te meurs" ou "Souviens-toi que tu vas mourir" ou « Souviens-toi que tu es en train de mourir ». " Stoicisme (Marc Aurèle, Sénèque, Épictète)

""Prends l’habitude de penser que la mort n’est rien pour nous. Car tout bien et tout mal résident dans la sensation : or la mort est privation de toute sensibilité. Par conséquent, la connaissance de cette vérité que la mort n’est rien pour nous, nous rend capables de jouir de cette vie mortelle, non pas en y ajoutant la perspective d’une durée infinie, mais en nous enlevant le désir de l’immortalité. Car il ne reste plus rien à redouter dans la vie, pour qui a vraiment compris que hors de la vie il n’y a rien de redoutable."  Epicure (341 – 270 av. J.-C.)